language: python

matrix:
  include:
    - env: TOX_ENV=py37-djangomaster
      python: 3.7
    - env: TOX_ENV=py36-djangomaster
      python: 3.6
    - env: TOX_ENV=py37-django30
      python: 3.7
    - env: TOX_ENV=py36-django30
      python: 3.6
    - env: TOX_ENV=py37-django22
      python: 3.7
    - env: TOX_ENV=py36-django22
      python: 3.6
    - env: TOX_ENV=flake8
    - env: TOX_ENV=docs
  allow_failures:
    - env: TOX_ENV=py37-djangomaster
      python: 3.7
    - env: TOX_ENV=py36-djangomaster
      python: 3.6
install: pip install tox

script: tox -e $TOX_ENV
